# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install system dependencies
RUN apk add --no-cache build-base libffi-dev openssl-dev gcc musl-dev

WORKDIR /app

# Copy project files into the container
COPY . /app

# Upgrade pip and install project dependencies
RUN pip install --upgrade pip && \
    pip install -e .

# Run the MCP server (via STDIO)
CMD ["ddg-mcp"]
