[project]
name = "ddg-mcp"
version = "0.1.1"
description = "DuckDuckGo search API MCP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "duckduckgo-search>=7.5.1",
 "mcp>=1.3.0",
 "beautifulsoup4",
 "fake-useragent",
 "lxml",
 "lxml_html_clean",
 "lxml_html_clean",
]
[[project.authors]]
name = "Shannon Sands"
email = "shannon.sands.1979@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
ddg-mcp = "ddg_mcp:main"
